M48
; DRILL file {KiCad 7.0.5} date Sun Aug  4 00:23:38 2024
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-08-04T00:23:38+08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.5
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.200
%
G90
G05
T1
X107.175Y-48.05
X107.175Y-86.15
X183.375Y-48.05
X183.375Y-86.15
T0
M30
